const CPE={version:"CPE-STATIC-2.1",store:"cpe-static-v2",seed:42};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const hash=t=>{let h=2166136261;for(let i=0;i<String(t).length;i++){h^=String(t).charCodeAt(i);h=Math.imul(h,16777619)}return("00000000"+(h>>>0).toString(16)).slice(-8)};
const iso=()=>new Date().toISOString(),clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),pct=x=>Math.round(x*100),num=(x,d=3)=>Number(Number(x).toFixed(d));
const esc=x=>String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const domains=[
{id:"P1",name:"Biological / Recovery",desc:"Recovery, energy, stress and biological resources.",traits:[["P1.1","Recovery Capacity","ability to restore resources","recovery_index"],["P1.2","Energy Regulation","available daily energy","energy_index"],["P1.3","Stress Load","acute/contextual load","stress_load"],["P1.4","Sleep Quality","recovery-supporting sleep","sleep_quality"]]},
{id:"P2",name:"Personality",desc:"Stable dispositions and response tendencies.",traits:[["P2.1","Emotional Regulation","regulation of affective responses","emotion_regulation"],["P2.2","Conscientiousness","consistency and responsibility","conscientiousness"],["P2.3","Openness","exploration and cognitive openness","openness"],["P2.4","Social Orientation","social engagement tendency","social_orientation"]]},
{id:"P3",name:"Cognitive-Behavioral",desc:"Reasoning, control, flexibility and execution.",traits:[["P3.1","Working Memory","maintenance/manipulation of information","working_memory"],["P3.2","Inhibitory Control","suppression of competing responses","inhibition"],["P3.3","Cognitive Flexibility","switching and adaptation","flexibility"],["P3.4","Planning","goal decomposition and sequencing","planning"]]},
{id:"P4",name:"Values",desc:"Priorities, principles and value consistency.",traits:[["P4.1","Integrity","alignment of principles and behavior","integrity"],["P4.2","Prosociality","orientation toward others","prosociality"],["P4.3","Autonomy","self-direction and agency","autonomy"],["P4.4","Long-term Orientation","weight on delayed outcomes","long_term"]]},
{id:"P5",name:"Execution",desc:"Translation of intention into repeatable action.",traits:[["P5.1","Execution Consistency","reliable completion across contexts","execution"],["P5.2","Adaptation","response to feedback","adaptation"],["P5.3","Goal Persistence","maintenance under friction","persistence"],["P5.4","Context Management","management of environmental constraints","context_management"]]}
];
const allTraits=domains.flatMap(d=>d.traits.map(t=>({id:t[0],name:t[1],definition:t[2],metric:t[3],domain:d.id,domainName:d.name})));
const state={profile:{P1:.68,P2:.71,P3:.76,P4:.82,P5:.59},traitScores:Object.fromEntries(allTraits.map((t,i)=>[t.metric,.55+((i*17)%35)/100])),daily:{stress:.25,fatigue:.22,recovery:.76,cognitiveLoad:.35,socialPressure:.2},selectedDomain:"P1",selectedTrait:"P1.1",events:[],runs:[],scenarios:[],claims:[],replications:[],provenance:[],experiment:{status:"DESIGNED",hypothesis:"Improved recovery and structured execution increase synthetic execution consistency.",trials:[]},transformation:{status:"READY",days:[],target:"Execution Consistency",rootCause:"Recovery / load imbalance"},report:null};
function save(){localStorage.setItem(CPE.store,JSON.stringify(state))}
function load(){try{const x=JSON.parse(localStorage.getItem(CPE.store)||"null");if(x)Object.assign(state,x)}catch(e){}}
function event(type,payload){const e={event_id:hash(type+JSON.stringify(payload)+iso()),type:type,timestamp:iso(),algorithm_version:CPE.version,input_hash:hash(JSON.stringify(payload)),output_hash:hash(type+JSON.stringify(payload)),scientific_status:"implementation_baseline"};state.provenance.push(e);return e}
function go(v){$$(".view").forEach(x=>x.classList.toggle("active",x.id==="view-"+v));$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v));window.scrollTo(0,0)}
$$(".nav").forEach(n=>n.onclick=()=>go(n.dataset.view));$$("[data-go]").forEach(n=>n.onclick=()=>go(n.dataset.go));
function renderOverview(){const k=[["Domains",5,"P1–P5"],["Traits",allTraits.length,"canonical ontology"],["Scenarios",state.scenarios.length,"browser definitions"],["Trials",state.experiment.trials.length,"synthetic"],["Claims",state.claims.length,"evidence-linked"],["Provenance",state.provenance.length,"audit events"]];$("#overviewKpis").innerHTML=k.map(x=>"<div class=\"kpi\"><span>"+x[0]+"</span><strong>"+x[1]+"</strong><em>"+x[2]+"</em></div>").join("");const p=["Question","Hypothesis","Measurement","Character","Transform","Compatibility","Experiment","QC","Analysis","Claim","Replication","Generalization","Report"];$("#pipeline").innerHTML=p.map((x,i)=>"<div class=\"pipe "+(state.experiment.trials.length&&i<10?"done":"")+"\"><b>"+(i+1)+"</b>"+x+"</div>").join("");$("#architecture").innerHTML=[["Ontology","Master Matrix","P1–P5 + traits"],["Runtime","Character Model","trait / state / capacity"],["Change","Transformation","root cause → intervention"],["Social","Compatibility","three vectors"],["Science","Research Engine","trials + QC"],["Evidence","Claim Graph","lineage + provenance"]].map(x=>"<div class=\"arch-node\"><b>"+x[0]+"</b>"+x[1]+"<small>"+x[2]+"</small></div>").join("");$("#health").innerHTML=[["Static runtime","READY","ok"],["Persistence","localStorage","ok"],["Determinism","seed "+CPE.seed,"ok"],["QC gate","before interpretation","ok"],["Empirical evidence","not established","warn"],["Production backend","not included","warn"]].map(x=>"<div class=\"health-row\"><span>"+x[0]+"</span><span class=\""+x[2]+"\">"+x[1]+"</span></div>").join("")}
function renderMatrix(){const d=domains.find(x=>x.id===state.selectedDomain);$("#domainList").innerHTML=domains.map(x=>"<div class=\"domain "+(x.id===state.selectedDomain?"active":"")+"\" data-domain=\""+x.id+"\"><b>"+x.id+" — "+x.name+"</b><span>"+x.desc+"</span></div>").join("");$$(".domain").forEach(x=>x.onclick=()=>{state.selectedDomain=x.dataset.domain;state.selectedTrait=domains.find(d=>d.id===state.selectedDomain).traits[0][0];renderMatrix()});const tr=d.traits.map(t=>({id:t[0],name:t[1],definition:t[2],metric:t[3]}));const s=tr.find(x=>x.id===state.selectedTrait)||tr[0];$("#traitInspector").innerHTML="<div class=\"panel-title\"><span>"+d.id+" — "+d.name+"</span><span class=\"small\">"+tr.length+" traits</span></div><div class=\"trait-list\">"+tr.map(t=>"<div class=\"trait\" data-trait=\""+t.id+"\"><b>"+t.id+" · "+t.name+"</b><span>"+t.definition+"</span></div>").join("")+"</div><div class=\"inspector\" style=\"margin-top:14px\">"+[["Definition",s.definition],["Metric",s.metric],["Current estimate",num(state.traitScores[s.metric])],["Evidence requirement","Measurement + behavioral observation"],["State interaction","Context can modulate observed behavior"],["Scientific status","Implementation contract"]].map(x=>"<div class=\"fact\"><label>"+x[0]+"</label><strong>"+x[1]+"</strong></div>").join("")+"</div>";$$(".trait").forEach(x=>x.onclick=()=>{state.selectedTrait=x.dataset.trait;renderMatrix()})}
function renderCharacter(){const bars=domains.map(d=>"<div class=\"bar-row\"><div class=\"bar-head\"><span>"+d.id+" · "+d.name+"</span><b>"+pct(state.profile[d.id])+"</b></div><div class=\"bar\"><i style=\"width:"+pct(state.profile[d.id])+"%\"></i></div></div>").join("");$("#profileBars").innerHTML=bars;const c=[["stress","Stress load"],["fatigue","Fatigue"],["recovery","Recovery"],["cognitiveLoad","Cognitive load"],["socialPressure","Social pressure"]];$("#stateControls").innerHTML=c.map(x=>"<div class=\"control\"><label><span>"+x[1]+"</span><b>"+pct(state.daily[x[0]])+"</b></label><input type=\"range\" min=\"0\" max=\"100\" value=\""+pct(state.daily[x[0]])+"\" data-state=\""+x[0]+"\"></div>").join("");$$("[data-state]").forEach(i=>i.oninput=()=>{state.daily[i.dataset.state]=Number(i.value)/100;renderCharacter();save()});const cap=clamp(state.profile.P5+state.daily.recovery*.18-state.daily.stress*.25-state.daily.fatigue*.18-state.daily.cognitiveLoad*.12),conf=clamp(.92-state.daily.stress*.12);$("#characterMetrics").innerHTML=[["Effective capacity",num(cap),"context-adjusted demonstration"],["Confidence",num(conf),"synthetic model confidence"],["Unknown load",.08,"missing evidence remains UNKNOWN"]].map(x=>"<div class=\"metric\"><span>"+x[0]+"</span><strong>"+x[1]+"</strong><small>"+x[2]+"</small></div>").join("");$("#decomposition").innerHTML="<div class=\"decomp\"><div class=\"decomp-box\"><b>TRAIT</b><span>Execution consistency = "+num(state.traitScores.execution)+". Stable estimate retained across current state changes.</span></div><div class=\"arrow\">+</div><div class=\"decomp-box\"><b>STATE</b><span>Current stress "+num(state.daily.stress)+" · fatigue "+num(state.daily.fatigue)+" · cognitive load "+num(state.daily.cognitiveLoad)+".</span></div></div>"}
function renderTransform(){$("#transformationFlow").innerHTML=[["Observe","current pattern"],["Root cause","load / recovery"],["Target","execution"],["Intervention","micro-task"],["Behavior","daily event"],["Adapt","reassess"]].map(x=>"<div class=\"flow-step\"><b>"+x[0]+"</b><span>"+x[1]+"</span></div>").join("");$("#intervention").innerHTML=[["Target",state.transformation.target],["Root cause",state.transformation.rootCause],["Protocol","Daily micro-task + recovery check + behavioral observation"],["Safety gate","Degrade load before promoting difficulty"],["Adaptation","Recalculate after each 7-day block"],["Status",state.transformation.status]].map(x=>"<div class=\"protocol-row\"><b>"+x[0]+"</b><span>"+x[1]+"</span></div>").join("");$("#trajectory").innerHTML=state.transformation.days.length?"<div class=\"trajectory\">"+state.transformation.days.map(d=>"<div class=\"day\" title=\"Day "+d.day+": "+d.value+"\" style=\"height:"+Math.round(20+d.value*145)+"px\"><span>"+d.day+"</span></div>").join("")+"</div>":"<div class=\"muted\">Run the 21-day simulation.</div>"}
function runTransformation(){const days=[];let v=state.profile.P5;for(let d=1;d<=21;d++){v=clamp(v+.012+state.daily.recovery*.004-state.daily.stress*.003);days.push({day:d,value:num(v,4),state_hash:hash(JSON.stringify({d:d,v:v}))})}state.transformation={status:"SIMULATED",days:days,target:"Execution Consistency",rootCause:"Recovery / load imbalance"};event("TRANSFORMATION_RUN",state.transformation);save();renderTransform();renderOverview()}
function renderCompatibility(){const A={recovery:.74,regulation:.78,values:.84,execution:.68},B={recovery:.63,regulation:.71,values:.88,execution:.74};$("#personA").innerHTML=Object.entries(A).map(x=>"<div class=\"bar-row\"><div class=\"bar-head\"><span>"+x[0]+"</span><b>"+pct(x[1])+"</b></div><div class=\"bar\"><i style=\"width:"+pct(x[1])+"%\"></i></div></div>").join("");$("#personB").innerHTML=Object.entries(B).map(x=>"<div class=\"bar-row\"><div class=\"bar-head\"><span>"+x[0]+"</span><b>"+pct(x[1])+"</b></div><div class=\"bar\"><i style=\"width:"+pct(x[1])+"%\"></i></div></div>").join("");const v=[["Cognitive / Behavioral",.74,"behavioral alignment"],["Values",.86,"principle alignment"],["Execution / Social",.69,"context-sensitive execution"]];$("#compatibilityVectors").innerHTML=v.map(x=>"<div class=\"vector\"><h3>"+x[0]+"</h3><div class=\"score\">"+pct(x[1])+"<small> / vector</small></div><div class=\"meter\"><i style=\"width:"+pct(x[1])+"%\"></i></div><span class=\"tag\">confidence 0.82</span><span class=\"tag\">synthetic</span><span class=\"tag\">"+x[2]+"</span></div>").join("");renderStress()}
function renderStress(){const base=[.74,.86,.69],sc=[["Normal",0],["High workload",-0.09],["Time pressure",-0.14],["Fatigue",-0.18],["Conflict",-0.12]];$("#stressResults").innerHTML="<div class=\"table-wrap\"><table><tr><th>Context</th><th>Cognitive</th><th>Values</th><th>Execution</th><th>Interpretation</th></tr>"+sc.map(s=>{const v=base.map((x,i)=>clamp(x+s[1]*(i===1?.35:1)));return "<tr><td>"+s[0]+"</td><td>"+pct(v[0])+"</td><td>"+pct(v[1])+"</td><td>"+pct(v[2])+"</td><td>context-sensitive synthetic result</td></tr>"}).join("")+"</table></div>"}
function renderScience(){const st=["Question","Hypothesis","Design","Trials","QC","Analysis","Replication","Generalization"];$("#scienceSteps").innerHTML=st.map((x,i)=>"<div class=\"science-step "+(i<6&&state.experiment.trials.length?"active":"")+"\">"+(i+1)+". "+x+"</div>").join("");$("#experimentMatrix").innerHTML="<div class=\"fact\"><label>Hypothesis</label><strong>"+state.experiment.hypothesis+"</strong></div><div class=\"fact\" style=\"margin-top:8px\"><label>Design</label><strong>2 × 2 synthetic factorial · deterministic seed "+CPE.seed+"</strong></div><div class=\"trait-list\">"+(state.scenarios.length?state.scenarios:[{id:"S01",conditions:{recovery:"high",load:"low"}},{id:"S02",conditions:{recovery:"low",load:"high"}}]).map(s=>"<div class=\"trait\"><b>"+s.id+"</b><span>"+esc(JSON.stringify(s.conditions))+"</span></div>").join("")+"</div>";const t=state.experiment.trials,p=t.filter(x=>x.qc==="PASS").length;$("#qc").innerHTML=[["Schema","PASS"],["Completeness",t.length?"PASS":"PENDING"],["Range validation",t.length?"PASS":"PENDING"],["Duplicate detection","PASS"],["Provenance",t.length?"PASS":"PENDING"],["QC gate",t.length?"OPEN":"CLOSED"]].map(x=>"<div class=\"health-row\"><span>"+x[0]+"</span><span class=\""+(x[1]==="PASS"||x[1]==="OPEN"?"ok":"warn")+"\">"+x[1]+"</span></div>").join("");$("#trialTable").innerHTML="<tr><th>Trial</th><th>Scenario</th><th>State</th><th>Intervention</th><th>Outcome</th><th>QC</th></tr>"+(t.length?t.map(x=>"<tr><td>"+x.id+"</td><td>"+x.scenario+"</td><td>"+x.state+"</td><td>"+x.intervention+"</td><td>"+x.outcome+"</td><td>"+x.qc+"</td></tr>").join(""):"<tr><td colspan=\"6\">No trials yet. Run Experiment.</td></tr>");if(t.length){const vals=t.map(x=>x.outcome),m=vals.reduce((a,b)=>a+b,0)/vals.length,sd=Math.sqrt(vals.reduce((a,b)=>a+(b-m)**2,0)/vals.length);$("#statistics").innerHTML="<div class=\"stat-grid\">"+[["N",vals.length],["Mean",num(m)],["SD",num(sd)],["QC pass",p+"/"+vals.length]].map(x=>"<div class=\"stat\"><span>"+x[0]+"</span><b>"+x[1]+"</b></div>").join("")+"</div>"}else $("#statistics").innerHTML="<div class=\"muted\">Statistics appear after trial execution.</div>";$("#replication").innerHTML=state.replications.length?state.replications.map(r=>"<div class=\"status-box\"><span>"+r.id+"</span><b>"+r.status+" · mean "+r.mean+"</b></div>").join(""):"<div class=\"muted\">Replication has not been run.</div>"}
function factorial(){state.scenarios=[];["low","high"].forEach((r,i)=>["low","high"].forEach((l,j)=>state.scenarios.push({id:"S"+(i*2+j+1),conditions:{recovery:r,load:l}})));event("FACTORIAL_GENERATED",{count:4,factors:["recovery","load"]});save();renderScience();renderOverview()}
function runExperiment(){if(!state.scenarios.length)factorial();const t=[];let k=1;for(const s of state.scenarios)for(let r=0;r<8;r++){const rec=s.conditions.recovery==="high"?0.12:0,load=s.conditions.load==="high"?-.1:0,noise=((parseInt(hash(s.id+":"+r),16)%100)/100-.5)*.18;t.push({id:"T"+String(k++).padStart(3,"0"),scenario:s.id,state:s.conditions.load,intervention:"structured micro-task",outcome:num(clamp(.68+rec+load+noise),4),qc:"PASS",synthetic:true})}state.experiment.trials=t;state.experiment.status="EXECUTED";event("EXPERIMENT_EXECUTED",{trials:t.length});save();renderScience();renderEvidence();renderOverview()}
function replicate(){if(!state.experiment.trials.length)runExperiment();const v=state.experiment.trials.map(x=>x.outcome),m=v.reduce((a,b)=>a+b,0)/v.length;state.replications=[1,2,3].map(i=>({id:"R00"+i,status:"REPRODUCED",mean:num(clamp(m+(i-2)*.006),4),n:v.length,empirical:false}));event("REPLICATION_EXECUTED",{count:3});save();renderScience();renderEvidence();renderOverview()}
function renderEvidence(){$("#evidenceGraph").innerHTML=["Question","Hypothesis","Experiment","Trial Data","QC","Analysis","Claim"].map((x,i)=>"<div class=\"e-node\"><b>"+x+"</b><span>"+(i<state.experiment.trials.length?"linked":"pending")+"</span></div>").join("");$("#claims").innerHTML=state.claims.length?state.claims.map(c=>"<div class=\"claim\"><b>"+c.id+"</b><p>"+c.statement+"</p><span class=\"tag\">"+c.status+"</span><span class=\"tag\">empirical=false</span></div>").join(""):"<div class=\"muted\">No claim validated yet.</div>";$("#claimGates").innerHTML=[["Implementation evidence",state.experiment.trials.length?"SUPPORTED":"PENDING"],["QC",state.experiment.trials.length?"PASS":"PENDING"],["Replication",state.replications.length?"SUPPORTED":"PENDING"],["Generalization","DESCRIPTIVE ONLY"],["Empirical validation","NOT ESTABLISHED"],["Clinical inference","NOT PERMITTED"]].map(x=>"<div class=\"status-box\"><span>"+x[0]+"</span><b class=\""+(x[1]==="SUPPORTED"||x[1]==="PASS"?"ok":"warn")+"\">"+x[1]+"</b></div>").join("")}
function validateClaims(){if(!state.experiment.trials.length)runExperiment();state.claims=[{id:"C-001",statement:"The configured synthetic CPE intervention scenario produces a measurable modeled execution outcome.",status:state.replications.length?"MODEL_REPLICATION_SUPPORTED":"IMPLEMENTATION_BASELINE",evidence:["Experiment","Trial Data","QC"],empirical:false,created_at:iso()}];event("CLAIM_VALIDATED",state.claims[0]);save();renderEvidence();renderOverview()}
function renderProvenance(){$("#provCount").textContent=state.provenance.length+" events";$("#provenanceTimeline").innerHTML=state.provenance.length?state.provenance.slice().reverse().map(e=>"<div class=\"timeline-item\"><div class=\"time\">"+e.timestamp.slice(0,19).replace("T"," ")+"</div><div><b>"+e.type+"</b><span>ID "+e.event_id+" · algorithm "+e.algorithm_version+"</span><span>input "+e.input_hash+" → output "+e.output_hash+"</span></div></div>").join(""):"<div class=\"muted\">No provenance events yet.</div>"}
function renderReport(){if(!state.report){$("#reportView").innerHTML="<div class=\"muted\">Generate the report after running the demonstration.</div>";return}const r=state.report;$("#reportView").innerHTML=[["Executive status","<p><b>"+r.scientific_status+"</b>. Deterministic synthetic browser execution.</p>"],["Methods","<p>Engine: "+r.methods.engine+"; seed: "+r.methods.seed+"; dataset: "+r.methods.data+".</p>"],["Model","<p>Ontology: "+r.ontology.domains+" domains / "+r.ontology.traits+" traits. Transformation: "+r.transformation.days+" days. Compatibility: "+r.compatibility.vectors+" vectors.</p>"],["Experiment","<p>Status: "+r.experiment.status+"; trials: "+r.experiment.trials+"; mean: "+(r.experiment.mean??"—")+"; QC: "+r.qc.gate+".</p>"],["Claims","<p>"+(r.claims.length?r.claims.map(c=>esc(c.statement)).join("<br>"):"No claims.")+"</p>"],["Limitations","<ul>"+r.limitations.map(x=>"<li>"+esc(x)+"</li>").join("")+"</ul>"]].map(x=>"<div class=\"report-section\"><h3>"+x[0]+"</h3>"+x[1]+"</div>").join("")}
function buildReport(){const v=state.experiment.trials.map(x=>x.outcome),m=v.length?v.reduce((a,b)=>a+b,0)/v.length:null;state.report={report_id:"RPT-"+hash(JSON.stringify(state)+iso()),generated_at:iso(),software_version:CPE.version,scientific_status:"IMPLEMENTATION_BASELINE",methods:{engine:"browser-native deterministic model",seed:CPE.seed,data:"synthetic"},ontology:{domains:5,traits:allTraits.length},transformation:{status:state.transformation.status,days:state.transformation.days.length},compatibility:{vectors:3,context_stress_test:true},experiment:{status:state.experiment.status,trials:v.length,mean:m===null?null:num(m)},qc:{gate:v.length?"PASS":"PENDING"},replication:{count:state.replications.length,status:state.replications.length?"DESCRIPTIVE_REPLICATION":"PENDING"},claims:state.claims,provenance_events:state.provenance.length,limitations:["Synthetic browser execution only","No empirical validation","No clinical inference","Generalization transport error is not estimated","localStorage is not production persistence"]};event("REPORT_GENERATED",state.report);save();renderReport()}
function development(){const r=[["V1.0","Master Matrix","Canonical ontology, P1–P5 domains, metrics and behavioral tests."],["V1.1","Runtime","Profiles, trait snapshots, daily state, capacity and decisions."],["V1.2","Research Execution","Study, protocol, experiment, participants, trials and QC."],["V1.4","Evidence Graph","Evidence/claim lineage and immutable provenance."],["V1.5","Replication / Generalization","Reproducibility and transport-context contracts."],["V1.6","Scientific Reporting","Structured report and evidence packaging."],["V1.7–V1.9","Decision → Orchestration → Synthetic E2E","Intervention, orchestration and end-to-end synthetic execution."],["V2.x","Science Lab / Operations","Experiment Matrix, operations and public static demonstrator."]];$("#developmentTimeline").innerHTML=r.map(x=>"<div class=\"release\"><strong>"+x[0]+"</strong><div><b>"+x[1]+"</b><span>"+x[2]+"</span></div></div>").join("")}
function runStress(){event("COMPATIBILITY_STRESS_TEST",{scenarios:5});save();renderCompatibility()}
function runTransformationAndSave(){runTransformation()}
function fullDemo(){factorial();runExperiment();replicate();validateClaims();runTransformation();runStress();buildReport();renderAll();go("overview")}
function renderAll(){renderOverview();renderMatrix();renderCharacter();renderTransform();renderCompatibility();renderScience();renderEvidence();renderProvenance();renderReport();development()}
function exportReport(){if(!state.report)buildReport();const b=new Blob([JSON.stringify(state.report,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="cpe-static-scientific-report.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$("#fullDemo").onclick=fullDemo;$("#runTransformation").onclick=runTransformationAndSave;$("#stressTest").onclick=runStress;$("#factorial").onclick=factorial;$("#runExperiment").onclick=runExperiment;$("#replicate").onclick=replicate;$("#validateClaims").onclick=validateClaims;$("#generateReport").onclick=buildReport;$("#exportReport").onclick=exportReport;$("#resetProfile").onclick=()=>{state.profile={P1:.68,P2:.71,P3:.76,P4:.82,P5:.59};renderCharacter();save()};$("#clearData").onclick=()=>{localStorage.removeItem(CPE.store);location.reload()};
load();event("STATIC_RUNTIME_READY",{version:CPE.version});save();renderAll();

/* Release A — Foundation upgrade: editable profile, explicit UNKNOWN/evidence model, and capacity decomposition. */
function releaseAFoundation(){
  const char=document.querySelector("#view-character");
  if(char && !document.querySelector("#profileBuilder")){
    const panel=document.createElement("article");
    panel.className="panel";
    panel.id="profileBuilder";
    panel.innerHTML='<div class="panel-title"><span>Profile Builder</span><span class="small">synthetic participant</span></div><div id="profileControls"></div>';
    const metrics=document.querySelector("#characterMetrics");
    metrics ? metrics.parentNode.insertBefore(panel,metrics) : char.appendChild(panel);
  }
  if(char && !document.querySelector("#unknownInspector")){
    const panel=document.createElement("article");
    panel.className="panel";
    panel.id="unknownInspector";
    panel.innerHTML='<div class="panel-title"><span>Evidence / UNKNOWN Inspector</span><span class="small">no artificial precision</span></div><div id="unknownGrid"></div>';
    char.appendChild(panel);
  }
  renderProfileFoundation();
}
function renderProfileFoundation(){
  const pc=document.querySelector("#profileControls");
  if(pc){
    pc.innerHTML=domains.map(d=>'<div class="control"><label><span>'+d.id+' · '+esc(d.name)+'</span><b>'+pct(state.profile[d.id])+'</b></label><input type="range" min="0" max="100" value="'+pct(state.profile[d.id])+'" data-profile="'+d.id+'"></div>').join("");
    $$("#profileControls [data-profile]").forEach(i=>i.oninput=()=>{
      state.profile[i.dataset.profile]=Number(i.value)/100;
      event("PROFILE_UPDATED",{domain:i.dataset.profile,value:state.profile[i.dataset.profile]});
      renderCharacter(); renderProfileFoundation(); save();
    });
  }
  const unknown=[
    ["P1.4","Sleep Quality","UNKNOWN","No direct measurement in demo profile"],
    ["P2.4","Social Orientation","PARTIAL","Synthetic trait estimate only"],
    ["P5.4","Context Management","UNKNOWN","Context-specific evidence absent"]
  ];
  const ug=document.querySelector("#unknownGrid");
  if(ug) ug.innerHTML='<div class="table-wrap"><table><tr><th>Trait</th><th>Evidence state</th><th>Confidence impact</th><th>Reason</th></tr>'+unknown.map(x=>'<tr><td>'+x[0]+' · '+x[1]+'</td><td><span class="tag">'+x[2]+'</span></td><td>reduced</td><td>'+x[3]+'</td></tr>').join("")+'</table></div>';
}
const _renderCharacterFoundation=renderCharacter;
renderCharacter=function(){_renderCharacterFoundation();releaseAFoundation();};
const _renderMatrixFoundation=renderMatrix;
renderMatrix=function(){
  _renderMatrixFoundation();
  const s=domains.find(d=>d.id===state.selectedDomain);
  const note=document.querySelector("#traitInspector .inspector");
  if(note && s){
    note.insertAdjacentHTML("beforeend",'<div class="fact"><label>Evidence state</label><strong>Measurement required · UNKNOWN preserved when absent</strong></div><div class="fact"><label>Transformation link</label><strong>Eligible target / state interaction contract</strong></div>');
  }
};
function releaseAStatus(){
  const foot=document.querySelector(".sidebar-foot");
  if(foot) foot.innerHTML='<b>'+CPE.version+'</b><span>Release A — Foundation</span><span>Implementation baseline · synthetic</span><span>Empirical validation: not established</span>';
}
const _renderAllFoundation=renderAll;
renderAll=function(){_renderAllFoundation();releaseAStatus();releaseAFoundation();};
