from enum import Enum

class CTEErrorCode(str, Enum):
    PRECONDITION_FAILED="PRECONDITION_FAILED"
    COMPATIBILITY_FAILED="COMPATIBILITY_FAILED"
    UNKNOWN_COMPATIBILITY="UNKNOWN_COMPATIBILITY"
    PROTOCOL_INVALID="PROTOCOL_INVALID"
    DETOX_REQUIRED="DETOX_REQUIRED"
    STABILIZATION_REQUIRED="STABILIZATION_REQUIRED"
    INTERVENTION_FAILED="INTERVENTION_FAILED"
    STATE_CAPTURE_FAILED="STATE_CAPTURE_FAILED"
    NO_STATE_CHANGE="NO_STATE_CHANGE"
    UNEXPECTED_CHANGE="UNEXPECTED_CHANGE"
    INVARIANT_FAILED="INVARIANT_FAILED"
    VALIDATION_FAILED="VALIDATION_FAILED"
    PROVENANCE_FAILED="PROVENANCE_FAILED"
    VERSION_CONFLICT="VERSION_CONFLICT"
    IDEMPOTENCY_CONFLICT="IDEMPOTENCY_CONFLICT"
    INTERVENTION_OUTCOME_UNKNOWN="INTERVENTION_OUTCOME_UNKNOWN"
    ROLLBACK_FAILED="ROLLBACK_FAILED"
    PARTIAL="PARTIAL"

class CTEError(RuntimeError):
    def __init__(self, code, message, details=None):
        super().__init__(message)
        self.code=code
        self.details=dict(details or {})
