-- Master Matrix V1.0 seed. Architecture/model only; not empirical validation.
BEGIN;
CREATE TABLE IF NOT EXISTS mm_trait_nodes(node_id TEXT PRIMARY KEY,parent_node_id TEXT,domain TEXT,node_kind TEXT,name_en TEXT,name_ru TEXT,state_trait TEXT,provenance TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS mm_trait_edges(edge_id BIGSERIAL PRIMARY KEY,from_node_id TEXT,to_node_id TEXT,edge_type TEXT,provenance TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS mm_metrics_catalog(metric_id TEXT PRIMARY KEY,node_id TEXT,metric_name TEXT,unit TEXT,range_min DOUBLE PRECISION,range_max DOUBLE PRECISION,data_source TEXT,provenance TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS mm_assessment_questions(question_id TEXT PRIMARY KEY,node_id TEXT,text_ru TEXT,text_en TEXT,scale TEXT,provenance TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS mm_behavioral_tests(test_id TEXT PRIMARY KEY,node_id TEXT,name TEXT,protocol TEXT,primary_metric TEXT,provenance TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS mm_load_levels(level_id TEXT PRIMARY KEY,name TEXT,social_pressure TEXT,cognitive_load TEXT,action_window TEXT,provenance TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS mm_adaptation_rules(rule_id TEXT PRIMARY KEY,condition_text TEXT,action TEXT,value_text TEXT,reason TEXT,provenance TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS mm_sprint_templates(sprint_id TEXT PRIMARY KEY,target_node_id TEXT,title TEXT,duration_days INT,supporting_habit TEXT,daily_action TEXT,level_progression JSONB,adaptation_rule_refs JSONB,evidence_status TEXT);
CREATE TABLE IF NOT EXISTS mm_roles(role_id TEXT PRIMARY KEY,name TEXT,dimensions JSONB);
CREATE TABLE IF NOT EXISTS mm_compatibility_rules(rule_id TEXT PRIMARY KEY,vector TEXT,inputs JSONB,outputs JSONB,status TEXT);
CREATE TABLE IF NOT EXISTS mm_claims(claim_id TEXT PRIMARY KEY,claim_text TEXT,status TEXT,provenance TEXT);
CREATE TABLE IF NOT EXISTS mm_validation_protocols(protocol_id TEXT PRIMARY KEY,name TEXT,status TEXT);
INSERT INTO mm_trait_nodes VALUES('P1',NULL,'P1','DOMAIN','Bio / Recovery','Био / Восстановление','STATE','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P2',NULL,'P2','DOMAIN','Personality','Личность','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P3',NULL,'P3','DOMAIN','Cognitive-Behavioral Regulation','Когнитивно-поведенческая регуляция','TRAIT','MIXED') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P4',NULL,'P4','DOMAIN','Values','Ценности','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P5',NULL,'P5','DOMAIN','Behavioral Execution','Поведенческое исполнение','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P1.1','P1','P1','TRAIT','Sleep Quality','Качество сна','STATE','RPT') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P1.2','P1','P1','TRAIT','Recovery Index','Индекс восстановления','STATE','RPT') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P1.3','P1','P1','TRAIT','Physical Activity','Физическая активность','STATE','RPT') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P1.4','P1','P1','TRAIT','Metabolic Stability','Метаболическая стабильность','STATE','RPT') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P1.5','P1','P1','TRAIT','Subjective Stress','Субъективный стресс','STATE','RPT') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P1.6','P1','P1','TRAIT','Subjective Energy','Субъективная энергия','STATE','RPT') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P2.1','P2','P2','TRAIT','Openness','Открытость','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P2.2','P2','P2','TRAIT','Conscientiousness','Добросовестность','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P2.3','P2','P2','TRAIT','Extraversion','Экстраверсия','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P2.4','P2','P2','TRAIT','Agreeableness','Доброжелательность','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P2.5','P2','P2','TRAIT','Neuroticism','Нейротизм','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P3.1','P3','P3','TRAIT','Impulse Control','Контроль импульсов','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P3.2','P3','P3','TRAIT','Pause Capacity','Способность к паузе','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P3.3','P3','P3','TRAIT','Cognitive Reappraisal','Когнитивная переоценка','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P3.4','P3','P3','TRAIT','Attention Regulation','Регуляция внимания','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P3.5','P3','P3','TRAIT','Reflection Depth','Глубина рефлексии','TRAIT','RPT') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P4.1','P4','P4','TRAIT','Honesty','Честность','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P4.2','P4','P4','TRAIT','Autonomy','Автономия','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P4.3','P4','P4','TRAIT','Achievement','Достижение','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P4.4','P4','P4','TRAIT','Security','Безопасность','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P4.5','P4','P4','TRAIT','Growth','Развитие','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P4.6','P4','P4','TRAIT','Compassion','Сострадание','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P4.7','P4','P4','TRAIT','Justice','Справедливость','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P4.8','P4','P4','TRAIT','Family','Семья','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P4.9','P4','P4','TRAIT','Freedom','Свобода','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P4.10','P4','P4','TRAIT','Order','Порядок','TRAIT','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P5.1','P5','P5','TRAIT','Discipline & Consistency','Дисциплина и последовательность','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P5.2','P5','P5','TRAIT','Social Courage & Assertiveness','Социальная смелость и ассертивность','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P5.3','P5','P5','TRAIT','Boundary Setting','Установление границ','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P5.4','P5','P5','TRAIT','Adaptability','Адаптивность','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P3.1.1','P3.1','P3','SUBTRAIT','Reactivity Reduction','Снижение реактивности','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P3.2.1','P3.2','P3','SUBTRAIT','Stimulus-Response Interval','Интервал стимул–реакция','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P3.2.2','P3.2','P3','SUBTRAIT','Pause Under Social Pressure','Пауза под социальным давлением','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P3.3.1','P3.3','P3','SUBTRAIT','Alternative Interpretation','Альтернативная интерпретация','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P3.4.1','P3.4','P3','SUBTRAIT','Task Focus','Фокус на задаче','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P3.5.1','P3.5','P3','SUBTRAIT','Trigger Reflection','Рефлексия триггеров','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P5.1.1','P5.1','P5','SUBTRAIT','Execution Consistency','Последовательность исполнения','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P5.2.1','P5.2','P5','SUBTRAIT','Disagreement Expression','Выражение несогласия','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P5.3.1','P5.3','P5','SUBTRAIT','Clear Refusal','Четкий отказ','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('P5.4.1','P5.4','P5','SUBTRAIT','Plan Reconfiguration','Перестройка плана','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('BLK.01',NULL,NULL,'BLOCKER','Low Recovery','Низкое восстановление','STATE','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('BLK.02',NULL,NULL,'BLOCKER','High Stress','Высокий стресс','STATE','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('BLK.03',NULL,NULL,'BLOCKER','Low Pause Capacity','Низкая способность к паузе','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('BLK.04',NULL,NULL,'BLOCKER','Low Execution Consistency','Низкая последовательность исполнения','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('BLK.05',NULL,NULL,'BLOCKER','Fear of Evaluation','Страх оценки','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('BLK.06',NULL,NULL,'BLOCKER','Low Boundary Clarity','Низкая ясность границ','TRAIT','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_nodes VALUES('BLK.07',NULL,NULL,'BLOCKER','Low Energy','Низкая энергия','STATE','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P3.1','P3.2','REQUIRES','MDL');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P3.1','P3.1.1','DECOMPOSES_TO','MDL');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P3.2','P3.2.1','DECOMPOSES_TO','MDL');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P3.2','P3.2.2','DECOMPOSES_TO','MDL');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P3.3','P3.3.1','DECOMPOSES_TO','EVD');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P3.4','P3.4.1','DECOMPOSES_TO','EVD');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P3.5','P3.5.1','DECOMPOSES_TO','RPT');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P5.1','P5.1.1','DECOMPOSES_TO','MDL');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P5.2','P5.2.1','DECOMPOSES_TO','MDL');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P5.3','P5.3.1','DECOMPOSES_TO','MDL');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P5.4','P5.4.1','DECOMPOSES_TO','MDL');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P3.2','BLK.03','BLOCKED_BY','MDL');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P5.1','BLK.04','BLOCKED_BY','MDL');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P5.2','BLK.05','BLOCKED_BY','MDL');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P5.3','BLK.06','BLOCKED_BY','MDL');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P3.1','BLK.01','STATE_MODULATOR','MDL');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P3.2','BLK.02','STATE_MODULATOR','MDL');
INSERT INTO mm_trait_edges(from_node_id,to_node_id,edge_type,provenance) VALUES('P5.1','BLK.07','STATE_MODULATOR','MDL');
INSERT INTO mm_metrics_catalog VALUES('M.P1.SLEEPQ','P1.1','Sleep quality','pct',0,100,'self_report_or_wearable','RPT') ON CONFLICT DO NOTHING;
INSERT INTO mm_metrics_catalog VALUES('M.P1.RECOVERY','P1.2','Recovery index','score',0,100,'wearable_or_self_report','RPT') ON CONFLICT DO NOTHING;
INSERT INTO mm_metrics_catalog VALUES('M.P1.STRESS','P1.5','Subjective stress','1-10',1,10,'daily_checkin','RPT') ON CONFLICT DO NOTHING;
INSERT INTO mm_metrics_catalog VALUES('M.P1.ENERGY','P1.6','Subjective energy','1-10',1,10,'daily_checkin','RPT') ON CONFLICT DO NOTHING;
INSERT INTO mm_metrics_catalog VALUES('M.P3.PAUSE','P3.2','Stimulus-response interval','seconds',0,NULL,'behavioral_test','DRV') ON CONFLICT DO NOTHING;
INSERT INTO mm_metrics_catalog VALUES('M.P3.IMPULSE','P3.1','Impulse-control success rate','pct',0,100,'behavioral_test','DRV') ON CONFLICT DO NOTHING;
INSERT INTO mm_metrics_catalog VALUES('M.P3.REAPPRAISAL','P3.3','Reappraisal task score','score',0,100,'behavioral_test','DRV') ON CONFLICT DO NOTHING;
INSERT INTO mm_metrics_catalog VALUES('M.P3.ATTENTION','P3.4','Attention regulation score','score',0,100,'task','DRV') ON CONFLICT DO NOTHING;
INSERT INTO mm_metrics_catalog VALUES('M.P3.REFLECTION','P3.5','Reflection completeness','pct',0,100,'journal','RPT') ON CONFLICT DO NOTHING;
INSERT INTO mm_metrics_catalog VALUES('M.P5.DISCIPLINE','P5.1','Routine completion','pct',0,100,'event_log','DRV') ON CONFLICT DO NOTHING;
INSERT INTO mm_metrics_catalog VALUES('M.P5.COURAGE','P5.2','Assertive action rate','pct',0,100,'event_log','DRV') ON CONFLICT DO NOTHING;
INSERT INTO mm_metrics_catalog VALUES('M.P5.BOUNDARY','P5.3','Boundary action rate','pct',0,100,'event_log','DRV') ON CONFLICT DO NOTHING;
INSERT INTO mm_metrics_catalog VALUES('M.P5.ADAPT','P5.4','Plan adaptation latency','minutes',0,NULL,'event_log','DRV') ON CONFLICT DO NOTHING;
INSERT INTO mm_metrics_catalog VALUES('M.CAP','ENGINE','Capacity index C_cap','score',NULL,NULL,'derived','DRV') ON CONFLICT DO NOTHING;
INSERT INTO mm_assessment_questions VALUES('Q.P3.2.01','P3.2','Когда возникает сильный триггер, удается ли вам заметить стимул до действия?','When a strong trigger occurs, can you notice the stimulus before acting?','1-5','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_assessment_questions VALUES('Q.P3.1.01','P3.1','Как часто вы действуете импульсивно, а затем жалеете о реакции?','How often do you act impulsively and later regret the reaction?','1-5','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_assessment_questions VALUES('Q.P3.3.01','P3.3','Можете ли вы сформулировать альтернативное объяснение неприятной ситуации?','Can you formulate an alternative interpretation of an unpleasant situation?','1-5','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_assessment_questions VALUES('Q.P5.1.01','P5.1','Какой процент запланированных коротких действий вы обычно доводите до конца?','What percentage of planned short actions do you usually complete?','0-100','RPT') ON CONFLICT DO NOTHING;
INSERT INTO mm_assessment_questions VALUES('Q.P5.3.01','P5.3','Насколько легко вам спокойно отказать в просьбе, которую вы не хотите выполнять?','How easy is it for you to calmly refuse a request you do not want to fulfill?','1-5','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_behavioral_tests VALUES('BT.P3.2.PAUSE','P3.2','10-second pause test','Standardized trigger vignette; record deliberate pause before response.','M.P3.PAUSE','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_behavioral_tests VALUES('BT.P3.1.IMPULSE','P3.1','Impulse inhibition trial','Repeated response-inhibition trials with predefined scoring and QC.','M.P3.IMPULSE','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_behavioral_tests VALUES('BT.P3.3.REAPPRAISAL','P3.3','Reappraisal task','Ambiguous negative scenario; collect initial and alternative interpretation.','M.P3.REAPPRAISAL','EVD') ON CONFLICT DO NOTHING;
INSERT INTO mm_behavioral_tests VALUES('BT.P5.1.EXEC','P5.1','Micro-routine completion','Seven-day short routine; count opportunities and completed executions.','M.P5.DISCIPLINE','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_behavioral_tests VALUES('BT.P5.3.BOUNDARY','P5.3','Boundary script trial','Standardized low-risk refusal scenario; score clarity and follow-through.','M.P5.BOUNDARY','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_load_levels VALUES('A','Recovery','none','minimal','5-30 sec','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_load_levels VALUES('B','Stabilization','none','low','1-3 min','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_load_levels VALUES('C','Training','low','medium','minutes','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_load_levels VALUES('D','Challenge','medium-high','high','real interaction','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_load_levels VALUES('E','Integration','real','full','real context','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_adaptation_rules VALUES('AR.01','stress >= 8 OR C_cap < 3','set_level','A','safety_degrade','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_adaptation_rules VALUES('AR.02','recovery < 4 for >= 3 consecutive days','set_level','A','pause_or_recovery','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_adaptation_rules VALUES('AR.03','valid_days >= 7 AND avg_compliance_7d >= 0.85 AND capacity_stable_7d == true','promote_one_level','','','DRV') ON CONFLICT DO NOTHING;
INSERT INTO mm_adaptation_rules VALUES('AR.04','compliance_7d < 0.50 AND stress >= 7','demote_one_level','','','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_adaptation_rules VALUES('AR.05','compliance_7d < 0.50 AND stress < 7','reduce_task_scope','50pct','','MDL') ON CONFLICT DO NOTHING;
INSERT INTO mm_adaptation_rules VALUES('AR.06','root_cause_score_missing == true','mark_unknown_and_collect_data','','','DRV') ON CONFLICT DO NOTHING;
INSERT INTO mm_sprint_templates VALUES('SPR-01','P3.2','Pause Capacity',21,'Sleep/recovery support','10-second pause','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_sprint_templates VALUES('SPR-02','P3.1','Impulse Control',21,'Recovery routine','Trigger → pause → response','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_sprint_templates VALUES('SPR-03','P3.3','Cognitive Reappraisal',21,'Reflection routine','Alternative interpretation','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_sprint_templates VALUES('SPR-04','P3.4','Attention Regulation',21,'Sleep schedule','Single-task focus block','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_sprint_templates VALUES('SPR-05','P3.5','Reflection Depth',21,'Evening wind-down','One trigger → one analysis','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_sprint_templates VALUES('SPR-06','P5.1','Discipline & Consistency',21,'Energy-aware planning','2-minute completion rule','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_sprint_templates VALUES('SPR-07','P5.2','Social Courage',21,'Recovery baseline','Low-risk disagreement','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_sprint_templates VALUES('SPR-08','P5.3','Boundary Setting',21,'Stress stabilization','One clear refusal','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_sprint_templates VALUES('SPR-09','P5.4','Adaptability',21,'Planning buffer','Replan after controlled disruption','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_sprint_templates VALUES('SPR-10','P3.1','Reactivity Reduction',21,'Stress logging','Trigger classification','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_sprint_templates VALUES('SPR-11','P5.1','Execution Consistency',21,'Routine anchoring','Same cue → same action','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_sprint_templates VALUES('SPR-12','P5.2','Assertive Communication',21,'Recovery check','Speak disagreement calmly','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_sprint_templates VALUES('SPR-13','P5.3','Boundary Maintenance',21,'Energy budget','State boundary and maintain it','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_sprint_templates VALUES('SPR-14','P3.2','Pause Under Social Pressure',21,'Recovery support','Pause before consequential response','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_sprint_templates VALUES('SPR-15','P5.4','Adaptive Planning',21,'Daily capacity check','Choose/revise plan from capacity','["B", "B", "C", "C", "D", "D", "E"]'::jsonb,'["AR.01", "AR.02", "AR.03", "AR.04", "AR.05"]'::jsonb,'MDL');
INSERT INTO mm_roles VALUES('ROLE.LEADER','Leader','{"initiative": "high", "decision_speed": "high", "structure": "medium"}'::jsonb);
INSERT INTO mm_roles VALUES('ROLE.STRATEGIST','Strategist','{"initiative": "medium", "decision_speed": "medium", "analysis": "high"}'::jsonb);
INSERT INTO mm_roles VALUES('ROLE.MEDIATOR','Mediator','{"conflict_management": "high", "assertiveness": "medium", "empathy": "high"}'::jsonb);
INSERT INTO mm_roles VALUES('ROLE.ORGANIZER','Organizer','{"structure": "high", "follow_through": "high", "adaptability": "medium"}'::jsonb);
INSERT INTO mm_compatibility_rules VALUES('CV1','V1_BIO_TEMPO','["P1.2", "P1.5", "P1.6"]'::jsonb,'["tempo_gap", "energy_gap", "reactivity_gap"]'::jsonb,'MDL');
INSERT INTO mm_compatibility_rules VALUES('CV2','V2_VALUES_ALIGNMENT','["P4.1", "P4.2", "P4.3", "P4.4", "P4.5", "P4.6", "P4.7", "P4.8", "P4.9", "P4.10"]'::jsonb,'["rank_correlation", "shared_priorities", "priority_gaps"]'::jsonb,'MDL');
INSERT INTO mm_compatibility_rules VALUES('CV3','V3_BEHAVIORAL_SYNERGY','["P5.1", "P5.2", "P5.3", "P5.4"]'::jsonb,'["role_pattern", "synergy", "friction"]'::jsonb,'MDL');
INSERT INTO mm_compatibility_rules VALUES('CV4','DATA_COMPLETENESS','["all_available_measurements"]'::jsonb,'["completeness", "recency", "consistency"]'::jsonb,'DRV');
INSERT INTO mm_claims VALUES('CLM-001','Adaptive task load can be operationalized from daily energy, stress and recovery inputs.','REGISTERED','MDL');
INSERT INTO mm_claims VALUES('CLM-002','A 21-day focused sprint can change the measured target behavior under a defined intervention protocol.','REGISTERED','HYP');
INSERT INTO mm_claims VALUES('CLM-003','Compatibility vectors can identify recurring friction and synergy patterns beyond a single scalar score.','REGISTERED','MDL');
INSERT INTO mm_claims VALUES('CLM-004','Trait changes should be evaluated longitudinally rather than inferred from short-term state fluctuations.','REGISTERED','MDL');
INSERT INTO mm_validation_protocols VALUES('VAL-01','Construct Validity','PLANNED');
INSERT INTO mm_validation_protocols VALUES('VAL-02','Intervention Efficacy','PLANNED');
INSERT INTO mm_validation_protocols VALUES('VAL-03','Compatibility Predictive Validity','PLANNED');
INSERT INTO mm_validation_protocols VALUES('VAL-04','Reproducibility','PLANNED');
COMMIT;